### ISSUE TITLE
Controls only visible first use, now invisible in editor

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#1061]
<b>BOLL[CodePlex]</b> <br />I have a WPF project on .NET 4.5.2, I installed Extended.Wpf.Toolkit through the NuGet package manager. I have Latest stable 2.9.0 installed.

I added the xmlns attribute to my window and things worked just fine. I got my IntegerUpDown in there and all was well. Close VS2015 Community and open it again, and the control is invisible. It still builds correctly and can be edited but it's just a transparent
 frame in the editor.

Fine, I can work with this. Now I wanted to use a DecimalUpDown, but that completely breaks, I get an exception, see attached image. The tag that was added is just empty. Other controls work but are as invisible as IntegerUpDown. DoubleUpDown breaks the same
 way DecimalUpDown does.

I've uninstalled and reinstalled without any difference, what is going on here? My application works fine outside of this, but I'm very new to Visual Studio so I might be missing something obvious.

**Comment by xceedsoftware** [comment]
<b>BOLL[CodePlex]</b> <br />OK, I finally found out why it breaks. 

I get this issue if I add a second platform in the Configuration Manager, then the controls become invisible and some of them just generate the above mentioned exceptions and errors.


I had added a separate x64 platform because I use 64-bit .DLLs. Now I instead edit the build settings in Properties and set x64 there and things work again. I discovered this by experimenting with a new project.


So to recreate the error do the following:

Start a new Visual C#  Windows  Classic Desktop  WPF Application With the project open, click down the dropdown at the top that says Debug, open the Configuration Manager.
Click the Any CPU drop-down and pick New..., pick a platform and press OK, I used x64 here.
Open your xaml and drag any control from WpfToolkit into the editor. It should either be invisible or give errors.

**Comment by xceedsoftware** [comment]
<b>BOLL[CodePlex]</b> <br />Adding to this. If I manually type in the tag for a DecimalUpDown, as just dragging it in from the Toolbox adds an empty tag, I get this message if I hover that line in the xaml. It's marked as having an issue.
'ParsingNumberStyle' property was already registered by 'Exceed_Wpf_Toolkit_CommonNumericUpDown`1_0_227006193'.

I've attached the message as well. Cleaning the solution does nothing.

**Comment by cwenger** [comment]
I believe I've had this same issue since I started using this package a few years ago. Whenever my project's build configuration is x64 instead of AnyCPU (not sure about x86), at design time I see red Xs where the Xceed controls should be, and errors. However, when I build the errors disappear and everything looks and works correctly.

**Comment by cwenger** [comment]
Here's a step-by-step of how to reproduce this issue:

1. Open Visual Studio.
2. Start a new WPF App project.
3. The solution and project default to AnyCPU build configuration. Add x64 solution and project build configurations.
4. Use NuGet to install Extended WPF Toolkit 3.1.0.
5. Go to MainWindow.xaml and add the appropriate XML namespace.
6. Add a DoubleUpDown control.

You should see the following error on the MainWindow designer:
![screen shot 2017-08-10 at 9 15 13 am](https://user-images.githubusercontent.com/1479224/29172215-407f85a6-7dad-11e7-8aa3-c1e008628776.png)

Also in the error list you should see:
> 'ParsingNumberStyle' property was already registered by 'Xceed_Wpf_Toolkit_CommonNumericUpDown`1_7_179465614'.

If you add an IntegerUpDown instead of a DoubleUpDown, there are no errors but it is invisible at design time. In both cases, everything works fine when running, it is a design-time issue only.

**Comment by XceedBoucherS** [comment]
Related to https://github.com/xceedsoftware/wpftoolkit/issues/1017
