### ISSUE TITLE
New problem loading dock layout with AvalonDock v3.2

### ISSUE THREAD

**Issue by cmkessell** [xceedsoftware/wpftoolkit#1202]
I recently updated AvalonDock from 3.1 to 3.2 and discovered a problem with saving and loading dock layouts using the built-in XML serializer.

Using an old test program I wrote while experimenting with AvalonDock 3.1, saving and reloading the layout correctly maintains my default dock/pane layout:

![image](https://user-images.githubusercontent.com/14317031/31382808-c59d3980-adb0-11e7-9d45-dfd705657946.png)

However, when the AvalonDock DLL is updated to 3.2 and the test is repeated the reloaded layout gets rearranged into vertical panes:

![image](https://user-images.githubusercontent.com/14317031/31382879-0047a548-adb1-11e7-9a75-3184467e920b.png)

Is this a bug or has there been some change in the AvalonDock usage/syntax which requires a change to my code?

**Comment by XceedBoucherS** [comment]
Hi,
It may be a bug, which could already be fixed in latest versions.
Can you submit a sample so we could test this ?
Thanks.

**Comment by cmkessell** [comment]
Hi,
As requested, find attached a zipped copy of my test program (including the AvalonDock 3.2 DLL).  I've modified the program to replace the menu bar with 2 buttons labelled SAVE LAYOUT and LOAD LAYOUT.  Clicking SAVE LAYOUT followed by LOAD LAYOUT should have no visible effect (and works fine with AvalonDock 3.1), but with AvalonDock 3.2 it exhibits the behaviour described earlier.

[AvalonDockDemo.zip](https://github.com/xceedsoftware/wpftoolkit/files/1371807/AvalonDockDemo.zip)

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v3.4.
In the meantime, go in file Xceed.Wpf.AvalonDock/Layout/LayoutRoot.cs,
1) add a using statement: 
using System.Windows.Controls;

2) In method "ReadXml":
Add the new variable :
Orientation orientation;

Replace the call to :
this.ReadRootPanel( reader );
with :
this.ReadRootPanel( reader, out orientation );

Replace the RootPanel creation :
this.RootPanel = new LayoutPanel();
with:
this.RootPanel = new LayoutPanel() { Orientation = orientation };

3) In method "ReadRootPanel":
Add a parameter :
out Orientation orientation

The first line would be :
orientation = Orientation.Horizontal;

The first line of the condition:
if( reader.LocalName.Equals( "RootPanel" ) )
should be
orientation = (reader.GetAttribute( "Orientation" ) == "Vertical") ? Orientation.Vertical : Orientation.Horizontal;

**Comment by cmkessell** [comment]
Hi, that worked well.  Thanks for the quick response.
