### ISSUE TITLE
TimePicker ValueChanged event only fires when control loses focus?

### ISSUE THREAD

**Issue by alewis-github** [xceedsoftware/wpftoolkit#1255]
I'm not sure if it's intended behaviour, but in my application the TimePicker ValueChanged handler only gets invoked once the control loses focus. I'm converting a Silverlight application which used the NumericUpDown control, and in that I have start/end datetimes, and incrementing the starttime hour spinner would automatically increment the enddate hour via the ValueChanged event handler - but now I can't do it.

Am I missing something here?

Thanks
Ade

**Comment by alewis-github** [comment]
Apologies - my description was maybe confusing above, but the situation is actually slightly worse!

1. The *TimePicker* ValueChanged event handler only gets called when the control loses focus.
2. The IntegerUpDown  ValueChanged event handler never gets called, under any circumstances?

Is this correct, or have I managed to do something unexpected?

Ade

**Comment by DUPadmin** [comment]
Agree with @alewis-github  DateTimePicker spinning buttons are not triggering ValueChanged until DateTimePicker loses focus. But does trigger Spinned event. 

I found this issue after updating Extended.Wpf.Toolkit from v3.0.0 to v3.2.0.

**Comment by alewis-github** [comment]
Yes, the spinned event fires, but before the value has changed, so you can’t actually use it as a value-changed event without doing some maths involving intervals, limits etc.

**Comment by XceedBoucherS** [comment]
Hi,

IntegerUpDown Valuechanged event is raised when the spinners are pressed.
In v3.2, TimePicker and DatetimePicker will not raise a ValueChanged event on spinning. This is fixed in v3.3 where each spinners press will raise the ValueChanged event.
v3.3 will be released shortly for Community Edition.
v3.6 is already available for Plus users here : https://xceed.com/xceed-toolkit-plus-for-wpf/

Thank you.
