### ISSUE TITLE
UI Automation problems in the DataGridControl in 3.3

### ISSUE THREAD

**Issue by grafster** [xceedsoftware/wpftoolkit#1289]
UI Automation seems to have taken a backwards step in 3.3 with the DataGridControl. Previously using "Visual UI Automation Verify", it had nodes for the grid, for the header and for each data item, which you could drill down into:-

![image](https://user-images.githubusercontent.com/7203957/37601840-f5c3692c-2b82-11e8-835e-07ab7cd6a91e.png)

Now there just seems to be a big long list of labels that make up the grid, with no way of telling which row they belong to, and no node for the grid:-

![image](https://user-images.githubusercontent.com/7203957/37601960-3d4df320-2b83-11e8-8005-79179fcbdbeb.png)

**Comment by XceedBoucherS** [comment]
Hi,
Sorry about that. 

During the v3.3 Release, UIAutomation have been implemented for all controls of the Toolkit Plus version only. So this is not included in the free version from GitHub.
Also, in v3.3, a major update of the DataGrid included in the Toolkit, have been done in order to increase its performance.
In the process, to be uniform through all Toolkit controls, the UIAutomation is now only part of the Toolkit Plus version.

If you still want to use the DataGrid's UIAutomation, you can get the Plus version from here (https://xceed.com/xceed-toolkit-plus-for-wpf/), or take the code from v3.2 on GitHub, which still contains the UIAutomation code for the DataGrid.
