### ISSUE TITLE
Serializing hidden elements does not work in AvalonDock 3.3 (and 3.2) Community Edition

### ISSUE THREAD

**Issue by petilaci** [xceedsoftware/wpftoolkit#1290]
When serializing some hidden panels, the hidden field contains duplicated properties (e.g. AutoHideMinWidth). When I try to deserialize the result of the previous serialization, I got an exception due to the invalid markup. I think this is the same issue as described here: https://github.com/xceedsoftware/wpftoolkit/issues/1126
When will this bug be fixed in the community version? Thank you!

**Comment by XceedBoucherS** [comment]
Hi,
As stated in #1126, this bug is fixed in the v3.4 version. 
"Plus" users already have it while "free" users will have it later, when v3.4 will be relesased to them.

You can see the "What's New" here : https://xceed.com/xceed-toolkit-plus-for-wpf/, to know what fixes are included in which version.
Thank you.
