### ISSUE TITLE
PropertyGrid failed to clear highlight when filter is cleard

### ISSUE THREAD

**Issue by raytangRT** [xceedsoftware/wpftoolkit#1336]
Problem:
---

When user typed in the filter textbox, the header is highlighted in yellow for matched item, but when user clear the filter by either [x] button or backspace, the highlight effect still presist

Screen:
---
![3](https://user-images.githubusercontent.com/30689714/41147640-8f657ebc-6b39-11e8-902d-cd2a3008cc8e.gif)

Sample:
---
```csharp
<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="Auto" />
        </Grid.ColumnDefinitions>
        
        <Button Width="50" Height="50" Name="button" />
        
    <xctk:PropertyGrid SelectedObject="{Binding ElementName=button}" Grid.Column="1">
        
    </xctk:PropertyGrid>
    </Grid>
```

Versions

xceed | .net
--- | ---
3.3.0 | 4.5.2

**Comment by XceedBoucherS** [comment]
Hi,

Thanks for the video and sample code.
This only happens in the free community version of the Toolkit. The Plus version do not have this issue.
It will be fixed in v3.8.

**Comment by raytangRT** [comment]
Hi, @XceedBoucherS, 

Thanks for the update, any tentative schedule for releasing version 3.8?

Thanks

**Comment by XceedBoucherS** [comment]
Hi,
It could take a while since the free version is always some versions behind the full version.
Currently,
Users of the Full version have v3.7
Users of the Free version have v3.4
Users of the Full version have more features and fast support(and some versions ahead). You can try the Full version for free here : http://xceed.com/xceed-toolkit-plus-for-wpf/
The Full and Free versions usually go up at about the same time.
Next release is scheduled later this year.
Thank you.

**Comment by raytangRT** [comment]
Thanks
