### ISSUE TITLE
Versions prior to 3.5 deleted from Nuget

### ISSUE THREAD

**Issue by dgosbell** [xceedsoftware/wpftoolkit#1499]
Can the versions prior to 3.5 (specifically 3.3) please be restored back to the nuget feed? 

I have some issue with Avalon Dock in 3.5 that I'm still trying to figure out (none of my anchorable windows are showing their views, just the name of their ViewModel) But now I can't build anything as when I tried to rollback my changes to use v3.3 of WPFToolkit it can no longer be dowloaded from nuget and it's not available on the GitHub releases either.

Please help as I'm trying to do some bug fixes on the current release for my project, but I can no longer build these due to version 3.3 being missing in nuget.

**Comment by Dirkster99** [comment]
Hi,

the nugets are not deleted but only [removed from listing](https://github.com/xceedsoftware/wpftoolkit/issues/1445#issuecomment-471617187). For debugging, you can still go back in time to version [3.3](https://github.com/xceedsoftware/wpftoolkit/tree/71a12b489e4ae669777f039038766cd764f3bce5) or [3.4](https://github.com/xceedsoftware/wpftoolkit/tree/24ecc09cf35e7095ad02d0beecfd5bafd83d0658) by compiling the libraries from source instead of using NuGet.

For AvalonDock 3.5, please check my branch as it seems to have [solved most critical](https://github.com/xceedsoftware/wpftoolkit/issues/1498) problems 3.5.

**Comment by dgosbell** [comment]
Yes, sorry it appears to have been some intermittent issue. I've tried again and nuget does return the 3.3 release even though it's not listed. And I've also figured out my issue with 3.5. It appears that the following line was changed

https://github.com/xceedsoftware/wpftoolkit/blob/aa93c693a581c6e97b7cec0c0d3c43faca4d1380/ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Themes/generic.xaml#L959

Which used to look like this (without the .Content on the Binding path)
```
Content="{Binding LayoutItem.View, RelativeSource={RelativeSource TemplatedParent}}" />
```

I'm using Caliburn.Micro as an MVVM framework and I've worked around this issue by adding the old theme back via a style in my project.

**Comment by Dirkster99** [comment]
Yes, I remember that one. Please be aware that you will run into more such problems as you use the open source version of AvalonDock 3.5. The list of issues we've found and fixed so far [can be seen here](https://github.com/Dirkster99/AvalonDock#Mile-Stone-History)
- Your issue was fixed at version 3.5.2 see 'Fixed Issue about PanesTemplateSelector being ignored'

I would strongly suggest to [use the nuget from my branch](https://www.nuget.org/packages/Dirkster.AvalonDock) unless you want to run into each of the problems listed and fix them on your own in your private branch...

**Comment by dgosbell** [comment]
Thanks @Dirkster99  I've switched my project over to use your branch which has let me delete that extra style that I don't really need. I really only need AvalonDock so this will also trim down my dependencies a bit.

PS. Thanks for publishing your articles on how you implemented AvalonDock in EDI it was really helpful to me in getting it to work with my project [DAX Studio](https://daxstudio.org) I'm just browsing through some of your other projects as I would like to implement a dark them option and it looks like some of your stuff might be useful there.

**Comment by Dirkster99** [comment]
Thats great to know - your DB app looks really cool :-) just spread the word and be sure to assign a ⭐️ where it helps you so others find these projects more easily...

**Comment by Dirkster99** [comment]
This project should be the most useful starting point if you look at theming (because you will find out that Dark themes will also make Light Highlighting definitions look aweful):
https://github.com/Dirkster99/AvalonEditHighlightingThemes

Therefore, I've extended the normal HighlightingManager in AvaloneEdit, implemented a ThemeableHighlightingManager and connected it with ThemesManager I am using for WPF. Now, all all aspected of colorization can be setup to work consistently.
