### ISSUE TITLE
could I use DateTimePicker alone, not include all controls 

### ISSUE THREAD

**Issue by zengyunchun** [xceedsoftware/wpftoolkit#1576]
I just want to use the DateTimePicker control, but must ref the toolkit lib about 1.1M size, it's too large for our project, could I just ref the DateTimerPicker only one alone ? thanks a lot !!

**Comment by XceedBoucherS** [comment]
Hi,

No, the DateTimePicker is part of the  Xceed Tookit and derives (and contains) other Xceed Toolkit controls. You must add a reference to Xceed.Wpf.Toolkit.dll.
Since referencing the Xceed Toolkit, you may find other controls useful for your application. Please try the LiveExplorer app showing all the Xceed Toolkit controls(https://xceed.com/xceed-toolkit-plus-for-wpf/).
