### ISSUE TITLE
PropertyGrid - Collections in sub items are not firing events or receiving templates

### ISSUE THREAD

**Issue by midspace** [xceedsoftware/wpftoolkit#1689]
The PropertyGrid is not applying Editor Definitions or receiving PropertyValueChanged event notifications from certain parts of a complex model.
Tested with version 4.1

This is a basic pseudocode of the model.
Properties in Model5 do not trigger the PropertyValueChanged event, and do not apply the EditorTemplateDeninifion.

```
Model1
{
string Property1
int Property2
Model2 Property3
Model3 Collection Property4
}

Model2
{
string Property1
int Property2
Model5 Collection Property3
}

Model3
{
string Property1
int Property2
Model4 Collection Property3
}

Model4
{
string Property1
int Property2
}

Model5
{
string Property1
int Property2
}

```

![image](https://user-images.githubusercontent.com/6026063/136853596-becdfc4f-9104-4086-af5d-8521f6894ea5.png)

Find attached a working sample of the code.
[WpfApp1-xceed propertygrid bugs.zip](https://github.com/xceedsoftware/wpftoolkit/files/7325259/WpfApp1-xceed.propertygrid.bugs.zip)

**Comment by XceedBoucherS** [comment]
Hi,
Thank you for the explanations and screenshots.
The issue has been identified and will be fixed in v4.3.

In the meantime, you can go in file Xceed.Wpf.Toolkit/PropertyGrid/Implementation/Editors/CollectionEditors.cs,
1) In method SetControlProperties() and Editor_CollectionUpdated()
Replace the lines:
var propertyGrid = propertyItem.ParentElement as PropertyGrid;
by;
var propertyGrid = this.GetParentPropertyGrid( propertyItem.ParentElement );

2) Add the following method:
 private PropertyGrid GetParentPropertyGrid( FrameworkElement element )
    {
      var propertyGrid = element as PropertyGrid;
      if( propertyGrid == null )
      {
        var parentPropertyItem = element as PropertyItem;
        while( ( parentPropertyItem != null ) && ( propertyGrid == null ) )
        {
          propertyGrid = parentPropertyItem.ParentElement as PropertyGrid;
          if( propertyGrid == null )
          {
            parentPropertyItem = parentPropertyItem.ParentElement as PropertyItem;
          }
        }
      }

      return propertyGrid;
    }

This will search the ancestor of type PropertyGrid to fix the issue for sub-Properties.
This will all be part of v4.3.
Thank you
