### ISSUE TITLE
BusyIndicator's BusyContent cannot be changed using binding?

### ISSUE THREAD

**Issue by PandaWood** [xceedsoftware/wpftoolkit#1748]
Confused that this doesn't work, the message (or BusyContent value) remains at the initial value set. 

I presume this is on purpose or what could I be doing wrong? Given that my code and xaml for the IsBusy property is almost identical and the IsBusy property binds/udpates and works fine
But whenever I set "BusyMessage" in the example below, the busy indicator never shows an updated value ie the BusyContent property is never updated

`<xctk:BusyIndicator IsBusy="{Binding IsBusy}" BusyContent="{Binding BusyMessage}">`

**Comment by XceedDanP** [comment]
Hello, is this still an issue for you?

I've tried it on my side with:
 - the latest code
 - .Net 4.8
 - DataContext set to an object that implements INotifyPropertyChanged, and with properties for IsBusy (bool) and BusyMessage (string) that notify changes

I don't see a problem so far on my side.

Maybe if you provide more information (toolkit version, .Net framework version, what kind of content is in BusyMessage, etc.), it might help to determine your exact situation.

Sincerely,
Dan
________________________________
From: Peter van der Woude ***@***.***>
Sent: Friday, May 19, 2023 1:40 AM
To: xceedsoftware/wpftoolkit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xceedsoftware/wpftoolkit] BusyIndicator's BusyContent cannot be changed using binding? (Issue #1748)


Confused that this doesn't work, the message (or BusyContent value) remains at the initial value set. There's no point binding it, because it doesn't work:
I presume this is on purpose or what could I be doing wrong? Given that my code and xaml for the IsBusy property is almost identical and the IsBusy property binds/udpates and works fine
But whenever I set "BusyMessage" in the example below, the busy indicator never shows an updated value.

<xctk:BusyIndicator IsBusy="{Binding IsBusy}" BusyContent="{Binding BusyMessage}">

**Comment by PandaWood** [comment]
Apologies, this ended up being my fault, confusing a similar named property that was bound to a different spinner.

**Comment by XceedDanP** [comment]
No worries, thanks for the update!
________________________________
