### ISSUE TITLE
Remove Xceed.Wpf.AvalonDock

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#655]
<b>mayerwin[CodePlex]</b> <br />Hello, 

Is there any way to remove the localization folders containing a single Xceed.Wpf.AvalonDock.resources.dll file when building a project?
Especially since I am not even using AvalonDock, it does not look very clean.

Thanks

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, You can remove those folders if you are not using AvalonDock. We will keep them for users who needs AvalonDock.

**Comment by jonrmorgan99** [comment]
Like the OP, I'm not using AvalonDock, but it is still included when building any project that uses an Xceed control. The localization folders really mess up my deployment.

I'm using v4.0.2 on net5. Is there any way I can prevent AvalonDock being included in my project builds ?

Thanks

**Comment by XceedBoucherS** [comment]
If you create a new application and use ManageNuGet packages, you can get Xceed Toolkit. From there, removing the AvalonDock dlls is a possibility.

If you have your own app, you can reference only Xceed.Wpf.Toolkit.dll and not reference the AvalonDock dlls.

**Comment by jonrmorgan99** [comment]
Thanks for the quick reponse. Just to check I understand what you are saying:

![image](https://user-images.githubusercontent.com/77990149/114840679-f5f17d00-9dce-11eb-81b5-201de639102e.png)

As you can see I have 4.0.2 installed for one project in my app. Here's the project structure in VS2019/net5 : 

![image](https://user-images.githubusercontent.com/77990149/114840934-37822800-9dcf-11eb-8cb2-7b567f03ed93.png)

It looks as though the Avalon dlls are required at compile time. 
There doesn't appear to any way to remove them. How do I do that?

Thanks

**Comment by XceedBoucherS** [comment]
After re-reading your question, I can see you are using a .net5 app. 
Xceed.Wpf.Toolkit v4.0.2 (free version) is currently only available for .NET Framework apps.
Xceed.Wpf.Toolkit v4.1 (commercial version) is currently available for .NET Framework and .NET Core apps.
Xceed.Wpf.Toolkit v4.2 (commerical version) will be available for .NET Framework,.NET Core and .NET5 apps.

So how are you using the free version of the Toolkit on a .NET 5 app ?
If I create a .NET Framework app and use ManageNuGet packages, you can get Xceed Toolkit v4.0.2. From there, removing the AvalonDock dlls is possible.
![github](https://user-images.githubusercontent.com/29377763/114865539-62b14b00-9dc0-11eb-9426-02de03c8a891.png)

**Comment by jonrmorgan99** [comment]
"Referencing .NET Framework 4.6.1 (and below) from .NET Core is a new feature available since .NET Core/Standard 2.0 preview 2 / VS 2017 preview 15.3, and according to MS, it can be thought of as a feature that helps you migrate .NET Framework code to .NET Standard or .NET Core over time."

[https://stackoverflow.com/questions/44861229/dotnet-restore-warning-nu1701](url)

So in net5 Xceed 4.0.2 is actually running under netfx, which seems quite magical to me.

Anyhow I still can't remove AvalonDock in my net5 app, but if I do find an answer I'll post an update

Thanks

**Comment by jonrmorgan99** [comment]
I'm still unable to find a way to remove Avalon Dock in net6. There seems to be no way to edit project references as in NetFX.

Has anyone else hit this problem in migrating from NetFX to Net5/6 ?

No doubt there's a simple answer but despite much searching I've yet to find it. As the OP said  (in 2017!) if you don't use Avalon Dock it just clutters up your output folder and adds lots of localization folders.

**Comment by zhongruijia** [comment]
这里是郭瑞的邮箱，已收到您的来件，我会尽快拜阅并给予您回复

**Comment by XceedBoucherS** [comment]
test comment

**Comment by XceedBoucherS** [comment]
test comment 2

**Comment by jonrmorgan99** [comment]
Still looking/waiting for some help on removing Avalon Dock and the localization folders, using Xceed Toolkit 4.4 in Net7 ?

Any ideas anyone ?

**Comment by XceedBoucherS** [comment]
Hi,
I just created a new .NET7 WPF Application.
Then I used "Manage NuGet Package" to install the latest free version of the Xceed Toolkit: "Extended.Wpf.Toolkit" v 4.5.
As you pointed out, the included package has the following dlls:
-Xceed.Wpf.AvalonDock.NET5.dll
-Xceed.Wpf.AvalonDock.Themes.Aero.NET5.dll
-Xceed.Wpf.AvalonDock.Themes.Metro.NET5.dll
-Xceed.Wpf.AvalonDock.Themes.VS2010.NET5.dll
-Xceed.Wpf.Toolkit.NET5.dll
and building the app results in many localization folders in the output folder.

But if, instead of installing the free version of Xceed Toolkit, if you install the paying version of Xceed Toolkit, you have many choices and one of them is to install only the Toolkit dll : "Xceed.Products.Wpf.Toolkit.Base" in "Manage NuGet Package". You will need to set the LicenseKey in code-behind (because using .NET5+):
Xceed.Wpf.Toolkit.Licenser.LicenseKey = "XXXXX-XXXXX-XXXXX-XXXX"; 
The license key can be found in folder "C:\Xceed Trial Keys" after installation and is valid for 45 days. You will have more controls and features than the free version.
After build the app, no localization folders appear in the output folder.

But if you still want to use the free version, maybe a post-build event in you app could be added to clean the unwanted localization folders of your output folder.

Thank you
