### ISSUE TITLE
UIAutomation for PropertyGrid

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#777]
<b>BoucherS[CodePlex]</b> <br />Would get the detail informations of the properties in the PropertyGrid control.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This will be fixed in v3.3 Plus. 

――――
Get more controls, features, updates and technical support with 
Xceed Toolkit Plus for WPF

**Comment by xceedsoftware** [comment]
<b>jjacks[CodePlex]</b> <br />i found it shocking that PropertyGrid simply does not list its content beyond categories. is there any workaround for that?

**Comment by tamasdeak93** [comment]
I use the Extended.Wpf.Toolkit NuGet package in my WPF project. The latest version is 3.2.0.
What should I do in order to make UIAutomation available? I found it on your website (https://xceed.com/forums/topic/propertygrid-ui-automation/) that it is available since March 2017. I don't get why your moderator is linking a .exe.
Please help me, so I can reach the Properties of my **xctk:PropertyGrid** . Where **xctk** is "http://schemas.xceed.com/wpf/xaml/toolkit"

**Comment by XceedBoucherS** [comment]
Hi,
Since v3.3, UIAutomation is working for all Toolkit's control, including the PropertyGrid.

This is a "Plus version" feature, which means it is not available for Community users.
You can try(and buy) a Plus version here : https://xceed.com/xceed-toolkit-plus-for-wpf/
Thanks.

**Comment by AhmedAbdohOrtiga** [comment]
Sorry to just be clear, as I understand UIA is working only with the paid version 3.3, so when would UIA work fine also for the free version?

**Comment by XceedBoucherS** [comment]
Hi,
It's a "Plus" version only feature.
At the moment, there is no plan to give it for free.
Thank you.
